# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NOSKode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, verbose_name='Team Name')),
                ('total_team_members', models.IntegerField(verbose_name='Total Team members')),
                ('team_leader', models.CharField(max_length=30, verbose_name='Team Leader')),
                ('phone_number', models.IntegerField(verbose_name='Phone no.')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('project_title', models.CharField(max_length=50, verbose_name='Project title')),
                ('project_description', models.TextField(verbose_name='Project Description')),
            ],
        ),
        migrations.CreateModel(
            name='Programming_Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_no', models.IntegerField(verbose_name='Phone no.')),
                ('programming_language', models.CharField(max_length=60, verbose_name='Programming Language')),
            ],
        ),
    ]
